### ISSUE TITLE
[UX] [appimage] Suggested changes to the top-bar (account management)

### ISSUE THREAD

**Issue by tangodev** [oneloveipfs/ipfsVideoUploader#55]
The current concept of "an account" is OK-ish, but can be improved. **Since I'm using only Avalon, my perspective may be much more narrow.**

I also don't know all of the features of the APIs, but it **seems** that all required pieces are there.

## Current state

IMHO the biggest issue is that I don't know what account I'm using at a given moment. There's no feeling of "a dashboard" or "control widget". 

![image](https://user-images.githubusercontent.com/12778629/112759103-caf6e300-8ff1-11eb-997b-6dbb8caf067a.png)

Compare this to DTube's own UX, where all the most important info is visible:

![dtube-top-bar-example](https://user-images.githubusercontent.com/12778629/112759305-a8b19500-8ff2-11eb-84b6-5950ba70d6e6.png)

## Suggestions

IMHO there should be more visibility as to "who am I?" and "what chain am I using?". Another candidate is "How much GB/day do I still have?" and "When should I refill my account at the current burn rate?".

![onelove-upper-bar-suggested-improvements-v3](https://user-images.githubusercontent.com/12778629/112759929-7a818480-8ff5-11eb-9969-9e2e47845fff.png)

Since this is more of an "individual feelings" kind of a thing, and not a "easy to understand bug" I'm open for a discussion. :smile: 

## Other issues

Affects: https://github.com/oneloveipfs/ipfsVideoUploader/issues/54

## Software details

Tested on `oneloveipfs-v2.0.2-linux-x64-remote.AppImage`
Tested on `Ubuntu 20.04 LTS`

**Comment by techcoderx** [comment]
The "logged in user" is displayed right below the "upload" button for a reason, is to ensure that everyone double-checks the account that they are posting with as it is very near to the button they are clicking (to transact) so that they don't post with the wrong account. It is way less likely that people would double-check when the name is displayed further away from that button.

When the hosting credits is running low (sufficient for less than 7 days) a warning sign will be displayed to notify the user to refill. There is no reason to clutter the top bar too much.
